### ISSUE TITLE
issue using catgirl.png

### ISSUE THREAD

**Issue by devenu85** [HansiMcKlaus/AudioSpectrumVisualizer#9]
``$PATH$\AudioSpectrumVisualizer-main\arguments.py:386: FutureWarning: `multichannel` is a deprecated argument name for `rescale`. It will be removed in version 1.0. Please use `channel_axis` instead.
  args.catgirlImage = rescale(args.catgirlImage, scale, anti_aliasing=True, preserve_range=True, multichannel=True)``

getting above warning .. when i am using catgirl argument..,

and getting output video with pic..

please fix the isuue.

**Comment by HansiMcKlaus** [comment]
Thanks for the bug report!

Fixed in d65d0dc7d376cb23131b3ff2d61807950708a270.

Also, the `catgirl` argument has been renamed to `image` and now requires a path to an image.

**Comment by devenu85** [comment]
> Thanks for the bug report!
> 
> Fixed in [d65d0dc](https://github.com/HansiMcKlaus/AudioSpectrumVisualizer/commit/d65d0dc7d376cb23131b3ff2d61807950708a270).
> 
> Also, the `catgirl` argument has been renamed to `image` and now requires a path to an image.

thank you brother.
